### ISSUE TITLE
toolrack 3.0.0 <--> query-exporter 2.2.1

### ISSUE THREAD

**Issue by polleke69** [albertodonato/toolrack#1]
When using query-exporter 2.2.1 in combination with toolrack 3.0.0.
Downgrading toolrack to 2.1.0 resolves the issue...

2020-05-20 11:43:45,502 - DEBUG - query-exporter - connected to database "test"
Exception in callback TimedCall._run(<generator ob...x7fce15b96a98>)
handle: <TimerHandle when=1981740.133866631 TimedCall._run(<generator ob...x7fce15b96a98>)>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/toolrack/aio/periodic.py", line 109, in _run
    self._func(*self._args, **self._kwargs)
TypeError: '_UnixSelectorEventLoop' object is not callable

**Comment by albertodonato** [comment]
Fixed by https://github.com/albertodonato/query-exporter/commit/d55f24fd6e91b2a5d85f657575c64d2fcb8879ed

I'm working on updating query-exporter to use toolrack 3.0.0

**Comment by imperatives** [comment]
@albertodonato I am experiencing this same issue with the 2.2.1 query-exporter release.  If I remove toolrack v. 3.0 and install v. 2.1.0 it appears to work great.

**Comment by albertodonato** [comment]
@polleke69 @imperatives could you please try with query-exporter 2.3.0?

If not, please open a bug on query-exporter including details of the (redacted as needed) config you're using.

**Comment by polleke69** [comment]
Perfect, that did the trick!
Thnx
